### PR TITLE
Japanese Support

### PR DESCRIPTION
**Pull request by Felli**
Not completed as of yet but I'm working on it slowly.

### CODE REVIEW

**Comment by bizley** [comment]
Wow, thank you!

Two changes are required though:
- rename `poduim` folder to `podium`
- Yii 2 core uses ISO code `ja` without locale part `JP` so I guess it's not necessary - please rename `ja-JP` to just `ja` (unless it's needed like in case of `pt-BR`)

**Comment by Felli** [comment]
Hopefully that fixed it, I'll be working offline for the rest of the translations then will update this afterward! :+1:

**Comment by bizley** [comment]
Cheers!

**Comment by bizley** [comment]
Actually, it supposed to be `ja/podium` instead of `podium/ja` 😄 I will modify it myself.

**Comment by Felli** [comment]
Ah sorry was in a hurry. xD

**Pull request merged**
